; Configuration file for EQRWS plugin to Windy
stationName = default
windyAPIKey = add-your-api-key-here
latitude = -43.530629
longitude = 172.636414
elevation = 10.0
transducer_height = 4.0
EQRWS_address = 192.168.100.100