; Configuration file for EQRWS plugin to Windy
[Plugin Configuration]
dataUploadPeriodSecs = 300
windGustDurationSecs = 3

[Windy Configuration]
stationNumber = 0
windyAPIKey = add-your-api-key-here

[EQRWS Configuration]
address = 192.168.100.100
seedlinkNetworkID = SS
seedlinkStationID = DEM2
seedlinkLocation = 10
seedlinkResolutionMicrounits = 1
seedlinkBand = L
seedlinkSource = W
seedlinkSubsourceWindSpeed = S
seedlinkSubsourceWindDir = D
seedlinkSubsourceTemperature = T
seedlinkSubsourcePressure = P
seedlinkSubsourceHumidity = H
seedlinkSubsourceRainIntensity = R
seedlinkSubsourceRainAccumulation = A